### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by zopyx** [rkhwaja/fs.dropboxfs#1]
Hi there,

I have a budget for sponsoring a Dropbox Pyfilesystem2 compatible driver.

Would you be interested? Can I reach you through email? Please reach out to info@zopyx.com
if you are interested.

**Comment by rkhwaja** [comment]
I'm afraid that I don't think that would mesh with my day job. Thanks though - someone else is welcome to contribute or fork while sponsored, of course.
